
CC=gcc
INSTALL=.
INCLUDE=$(INSTALL)/include -I.
LIBS=$(INSTALL)/lib -lreadline 
LFLAGS=-L$(LIBS) -Wl,-rpath=$(LIBS) -lmylib
CFLAGS=-Wall -g  -I$(INCLUDE) $(GITDEV)
PROGS=library loop mydash

all: $(PROGS) dox

loop: loop.o
	$(CC) $(CFLAGS) -o $@  $<

mydash: mydash.o error.o
	$(CC) $(CFLAGS) -o $@ $^ $(LFLAGS)

library:
	cd libsrc; make install; cd ..
##
## on every build, record the working copy revision string
##
svn_version.c: FORCE
		echo -n 'const char* svn_version(void) { const char* SVN_Version = "' > svn_version.c
		svnversion -n . >> svn_version.c
		echo '"; return SVN_Version; }' >> svn_version.c
			
FORCE:
##
## Then any executable that links in svn_version.o will be able
## to call the function svn_version() to get a string that
## describes exactly what revision was built.

	
	

dox:
	echo "Generating documentation using doxygen..."
	doxygen doxygen-config > doxygen.log
	echo "Use konqueror docs/html/index.html to see docs (or any other browser)"

remake: clean all

clean:
	cd libsrc; make clean; cd ..
	
	
	/bin/rm -f *.o $(PROGS) a.out core  *.log
	/bin/rm -fr docs
	cd include; rm -fr *.h
	cd lib; rm -rf libmylib.* 
